# Generated by Django 5.2.1 on 2025-05-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super-Admin'), ('admin', 'Admin'), ('user', 'User')], max_length=20, null=True),
        ),
    ]
