# Generated by Django 5.2.1 on 2025-05-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='priotriy',
            new_name='priority',
        ),
    ]
